if(WIN32)
  set(YLT_NETWORKDIRECT_ROOT "" CACHE PATH "Path to the root folder of NetworkDirect SDK")
  if(EXISTS "${YLT_NETWORKDIRECT_ROOT}/lib/x64/ndutil.lib")
    # NetworkDirect SDK installed with Nuget
    set(YLT_NETWORKDIRECT_INCLUDE_DIR "${YLT_NETWORKDIRECT_ROOT}/include")
    set(YLT_NETWORKDIRECT_LIB_DIR "${YLT_NETWORKDIRECT_ROOT}/lib/x64")
    set(YLT_HAVE_ND ON)
    message(STATUS "Using NetworkDirect from pre-built package: ${YLT_NETWORKDIRECT_INCLUDE_DIR} ${YLT_NETWORKDIRECT_LIB_DIR}")
  elseif(EXISTS "${CMAKE_TOOLCHAIN_FILE}")
    # NetworkDirect SDK installed with vcpkg
    get_filename_component(YLT_VCPKG_CMAKE "${CMAKE_TOOLCHAIN_FILE}" NAME)
    get_filename_component(YLT_VCPKG_BUILDSYSTEM_PATH "${CMAKE_TOOLCHAIN_FILE}" PATH)
    if("${YLT_VCPKG_CMAKE}" STREQUAL "vcpkg.cmake")
      get_filename_component(YLT_VCPKG_LIB_INSTALLED_PATH "${YLT_VCPKG_BUILDSYSTEM_PATH}/../../installed/x64-windows" ABSOLUTE)
      set(YLT_NETWORKDIRECT_INCLUDE_DIR "${YLT_VCPKG_LIB_INSTALLED_PATH}/include")
      set(YLT_NETWORKDIRECT_LIB_DIR "${YLT_VCPKG_LIB_INSTALLED_PATH}/lib")
    endif()
    if(EXISTS "${YLT_NETWORKDIRECT_LIB_DIR}/ndutil.lib")
      set(YLT_HAVE_ND ON)
      message(STATUS "Using NetworkDirect from vcpkg: ${YLT_NETWORKDIRECT_INCLUDE_DIR} ${YLT_NETWORKDIRECT_LIB_DIR}")
    else()
      set(YLT_HAVE_ND OFF)
    endif()
  else()
    set(YLT_HAVE_ND OFF)
  endif()
endif()
